// src/assets/sureler.js
export const sureler = {
    bismillah: {
        latin: "Bismillâhir Rahmânir Rahîm",
        arabic: "بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيمِ"
    },
    sadakallah: {
        latin: "Sadakallâhul-Azîm",
        arabic: "صَدَقَ اللّٰهُ الْعَظِيمُ"
    },
    // Bakara Sûresi 2/255. Ayet
    kursi: {
        latin: [
            "Allâhü lâ ilâhe illâ hüvel Hayyü’l-Kayyûm.",
            "Lâ te’huzuhû sinetün ve lâ nevm.",
            "Lehu mâ fî’s-semâvâti ve mâ fî’l-ard.",
            "Men zellezî yeşfeu indehû illâ bi-iznih.",
            "Ya’lemu mâ beyne eydîhim ve mâ halfehum.",
            "Ve lâ yuhîtûne bi şey’in min ilmihî illâ bimâ şâe.",
            "Vesia kursiyyuhus-semâvâti ve’l-ard.",
            "Ve lâ yeûduhû hıfzuhümâ.",
            "Ve hüve’l-Aliyyu’l-Azîm."
        ],
        arabic: [
            "اَللّٰهُ لَٓا اِلٰهَ اِلَّا هُوَۚ اَلْحَيُّ الْقَيُّومُۚ",
            "لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌؕ",
            "لَهُ مَا فِي السَّمٰوَاتِ وَمَا فِي الْاَرْضِؕ",
            "مَنْ ذَا الَّذٖي يَشْفَعُ عِنْدَهُٓ اِلَّا بِاِذْنِهٖؕ",
            "يَعْلَمُ مَا بَيْنَ اَيْدٖيهِمْ وَمَا خَلْفَهُمْۚ",
            "وَلَا يُحٖيطُونَ بِشَيْءٍ مِنْ عِلْمِهٖٓ اِلَّا بِمَا شَٓاءَۚ",
            "وَسِعَ كُرْسِيُّهُ السَّمٰوَاتِ وَالْاَرْضَۚ",
            "وَلَا يَؤُ۫دُهُ حِفْظُهُمَاۚ وَهُوَ الْعَلِيُّ الْعَظٖيمُ"
        ]
    },
    // Bakara Sûresi 2/285-286. Ayet
    amanerRasulu: {
        latin: [
            "Âmener rasûlü bimâ ünzile ileyhi min rabbihi velmü'minûn;",
            "kûllün âmena billâhi ve melâiketihî ve kûtubihî ve rusulihî;",
            "lâ nüferriku beyne ehadim min rusulih.",
            "Ve kâlû semi'nâ ve ata'nâ; gufrâneke rabbenâ ve ileykel mesîr.",
            "Lâ yukellifullâhü nefsen illâ vüs‘ahâ;",
            "lehâ mâ kesebet ve aleyhâ mektesebet.",
            "Rabbenâ lâ tuâhiznâ in nesînâ ev ahta‘nâ;",
            "rabbenâ velâ tahmil aleynâ isran kemâ hameltehû alellezîne min kablinâ;",
            "rabbenâ velâ tuḥammilnâ mâ lâ tâkate lenâ bihî;",
            "va‘fu annâ, vağfir lenâ, verḥamnâ;",
            "ente mevlânâ fensurnâ alel kavmil kâfirîn."
        ],
        arabic: [
            "اٰمَنَ الرَّسُولُ بِمَٓا اُنْزِلَ اِلَيْهِ مِنْ رَبِّهٖ وَالْمُؤْمِنُونَؕ",
            "كُلٌّ اٰمَنَ بِاللّٰهِ وَمَلٰٓئِكَتِهٖ وَكُتُبِهٖ وَرُسُلِهٖؕ",
            "لَا نُفَرِّقُ بَيْنَ اَحَدٍ مِنْ رُسُلِهٖࣞ",
            "وَقَالُوا سَمِعْنَا وَاَطَعْنَا غُفْرَانَكَ رَبَّنَا وَاِلَيْكَ الْمَصٖيرُ",
            "لَا يُكَلِّفُ اللّٰهُ نَفْساً اِلَّا وُسْعَهَاؕ",
            "لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْؕ",
            "رَبَّنَا لَا تُؤَاخِذْنَٓا اِنْ نَسٖينَٓا اَوْ اَخْطَأْنَاۚ",
            "رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَٓا اِصْراً كَمَا حَمَلْتَهُ عَلَى الَّذٖينَ مِنْ قَبْلِنَاۚ",
            "رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهٖۚ",
            "وَاعْفُ عَنَّاࣞ وَاغْفِرْ لَنَاࣞ وَارْحَمْنَاࣞ",
            "اَنْتَ مَوْلٰينَا فَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرٖينَ"
        ]
    },
    // Fetih Sûresi 48
    fetih: {
        latin: [
            "Lekad sadekallâhu resûlehur ru’yâ bil hakk.",
            "Le tedḥulûnnel mescidel harâme inşâ allâhu âminîne,",
            "muhallikîne ruûse-kum ve mukassirîne, Lâ tehâfûn.",
            "Fe alime mâ lem ta’lemû fe ce’ale min dûni zâlike fethan karîbâ.",
            "Hüvellezî ersele resûlehü bil hüdâ ve dînil hakkî",
            "liyüzhire hü alâ’d-dîni kullihî,",
            "ve kefâ billâhi şehîdâ.",
            "Muhammedün resûlullâh.",
            "Vellezîne me’ahû eşiddâu alel-küffâri ruhamâu beynehüm.",
            "Terâhüm rükke’an sücceden yebteğûne fadlen minallâhi ve rıdvânen.",
            "Sîmehüm fî vücûhihim min eserî’s-sücûd.",
            "Zâlike meselühum fî’t-tevrâh.",
            "Ve meselühum fî’l-incîl,",
            "keẕer’in ahrece şet’ahu feâẕerehû festağlaza festevâ alâ sûkıhî",
            "yu’cibü’ẕ-ẕu’râ’a li-yeğîze bihimü’l-küffâr.",
            "Veâdâllâhul leẕîne âmenû ve amilû’s-sâlihâti minhüm",
            "mağfiraten ve ecran azîmâ."
        ],
        arabic: [
            "لَقَدْ صَدَقَ اللّٰهُ رَسُولَهُ الرُّءْيَا بِالْحَقِّۚ",
            "لَتَدْخُلُنَّ الْمَسْجِدَ الْحَرَامَ اِنْ شَٓاءَ اللّٰهُ اٰمِنٖينَۙ",
            "مُحَلِّقٖينَ رُؤُ۫سَكُمْ وَمُقَصِّرٖينَۙ لَا تَخَافُونَؕ",
            "فَعَلِمَ مَا لَمْ تَعْلَمُوا فَجَعَلَ مِنْ دُونِ ذٰلِكَ فَتْحاً قَرٖيباً",
            "هُوَ الَّـذٖٓي اَرْسَلَ رَسُولَهُ بِالْهُدٰى وَدٖينِ الْحَقِّ",
            "لِيُظْهِرَهُ عَلَى الدّٖينِ كُلِّهٖؕ",
            "وَكَفٰى بِاللّٰهِ شَهٖيداًؕ",
            "مُحَمَّدٌ رَسُولُ اللّٰهِؕ",
            "وَالَّذٖينَ مَعَهُٓ اَشِدَّٓاءُ عَلَى الْكُفَّارِ رُحَمَٓاءُ بَيْنَهُمْ",
            "تَرٰيهُمْ رُكَّعاً سُجَّداً يَبْتَغُونَ فَضْلاً مِنَ اللّٰهِ وَرِضْوَاناًؗ",
            "سٖيمَاهُمْ فٖي وُجُوهِهِمْ مِنْ اَثَرِ السُّجُودِؕ",
            "ذٰلِكَ مَثَلُهُمْ فِي التَّوْرٰيةِۚۛ",
            "وَمَثَلُهُمْ فِي الْاِنْجٖيلِࣞۛ",
            "كَزَرْعٍ اَخْرَجَ شَطْـَٔهُ فَاٰزَرَهُ فَاسْتَغْلَظَ فَاسْتَوٰى عَلٰى سُوقِهٖ",
            "يُعْجِبُ الزُّرَّاعَ لِيَغٖيظَ بِهِمُ الْكُفَّارَؕ",
            "وَعَدَ اللّٰهُ الَّذٖينَ اٰمَنُوا وَعَمِلُوا الصَّالِحَاتِ مِنْهُمْ",
            "مَغْفِرَةً وَاَجْراً عَظٖيماً"
        ]
    },
    // Haşir Sûresi 59
    hasir: {
        latin: [
            "Lâ yestevî ashâbun-nâr ve ashâbul-cennet,",
            "ashâbul-cennet hümül-fâizûn.",
            "Lev enzelnâ hâzâl-Kur'ân alâ cebelin le-raeytehû ",
            "hâşi’en mutasaddi’an min haşyetillâh.",
            "Ve tilkel-emsâl nadribuhâ lin-nâsi leallehüm yetefekkerûn.",
            "Hüvellâhüllezi lâ ilâhe illâ hü,",
            "âlimül-ğaybi veş-şehâde.",
            "Hüver-rahmânür-rahîm.",
            "Hüvellâhüllezi lâ ilâhe illâ hü,",
            "el-Melikül-Kuddûs, es-Selâmül-Mü’minül-Müheyminül",
            "Azîzül-Cebbârül-Mütekebbir.",
            "Sübhânallâhi ammâ yüşrikûn.",
            "Hüvellâhül-hâlikül-bâri’ül-musavvir.",
            "Lehül-esmâul-husnâ.",
            "Yüsebbihu lehû mâ fis-semâvâti vel-ard.",
            "Ve hüvel-azîzül-hakîm."
        ],
        arabic: [
            "لَا يَسْتَـوٖٓي اَصْحَابُ النَّارِ وَاَصْحَابُ الْجَنَّةِؕ",
            "اَصْحَابُ الْجَنَّةِ هُمُ الْـفَٓائِزُونَ",
            "لَوْ اَنْزَلْنَا هٰذَا الْقُرْاٰنَ عَلٰى جَبَلٍ",
            "لَرَاَيْتَهُ خَاشِعاً مُتَصَدِّعاً مِنْ خَشْيَةِ اللّٰهِؕ",
            "وَتِلْكَ الْاَمْثَالُ نَضْرِبُهَا لِلنَّاسِ لَعَلَّهُمْ يَتَفَكَّرُونَ",
            "هُوَ اللّٰهُ الَّذٖي لَٓا اِلٰهَ اِلَّا هُوَۚ",
            "عَالِمُ الْغَيْبِ وَالشَّهَادَةِۚ",
            "هُوَ الرَّحْمٰنُ الرَّحٖيمُ",
            "هُوَ اللّٰهُ الَّذٖي لَٓا اِلٰهَ اِلَّا هُوَۚ",
            "اَلْمَلِكُ الْقُدُّوسُ السَّلَامُ الْمُؤْمِنُ الْمُهَيْمِنُ",
            "الْعَزٖيزُ الْجَبَّارُ الْمُتَكَبِّرُؕ",
            "سُبْحَانَ اللّٰهِ عَمَّا يُشْرِكُونَ",
            "هُوَ اللّٰهُ الْخَالِقُ الْبَارِئُ الْمُصَوِّرُ لَهُ الْاَسْمَٓاءُ الْحُسْنٰىؕ",
            "يُسَبِّـحُ لَهُ مَا فِي السَّمٰوَاتِ وَالْاَرْضِۚ",
            "وَهُوَ الْعَزٖيزُ الْحَكٖيمُ"
        ]
    },
    // Nebe Sûresi 78
    nebe: {
        latin: [
            "Amme yetesâelûn.",
            "Anin nebei’l azîm.",
            "Ellezî hüm fîhi muḥtelifûn.",
            "Kellâ seya’lemûn.",
            "Sümme kellâ seya’lemûn.",
            "Elem nece’alil arda mihedâ.",
            "Vel cibâle evtâdâ.",
            "Ve ḥalaknâküm eẕvâcâ.",
            "Ve cealne nevmeküm sûbâtâ.",
            "Ve cealnel leyle libâsâ.",
            "Ve cealnen nehera meâşâ.",
            "Ve beneyne fevkaküm seb’an şidâdâ.",
            "Ve cealne sirâcen vehhecâ.",
            "Ve enzelne minel mu’sırâti mâen s̱eccâcâ.",
            "Li nuhrice bihî habben ve nebâtâ.",
            "Ve cennetin elfâfâ.",
            "İnne yevmel fasli kâne mîkâtâ.",
            "Yevme yunfeḥu fîs-suri fe te’tune efvâcâ.",
            "Ve futihatis-semâu fe kânet ebvâbâ.",
            "Ve suyyirat-il cibâlû fe kânet serâbâ.",
            "İnne cehenneme kânet mirsâde.",
            "Lit-tâğîne me âbâ.",
            "Lâbis̱îne fîhe ahkâbâ.",
            "Lâ yaẕûkûne fîhe berden ve lâ şarâbe.",
            "İllâ hamîmen ve ğassâkâ.",
            "Cezâen vifâkâ.",
            "İnnehum kânû lâ yercûne hisâbâ.",
            "Ve keẕẕebû bi âyâtinâ kiẕẕâbâ.",
            "Ve külle şey'in ahsâynâhü kitâbâ.",
            "Feẕukû felen neẕîdeküm illâ aẕâbâ.",
            "İnne lil muttekîne mefâzâ",
            "Hadâika ve a’nâbâ",
            "Ve kevâ’ibe etrâbâ",
            "Ve ke’sen dihâkâ",
            "Lâ yesme’ûne fîhâ lağven ve lâ kizzâbâ",
            "Cezâen min rabbike ‘atâen hisâbâ.",
            "Rabbis semâvâti vel ardi ve mâ beynehumâr rahmâni lâ yemlikûne minhu hitâbâ",
            "Yevme yekûmur rûhu vel melâiketu saffâ, lâ yetekellemûne illâ men ezine lehur rahmânu ve kâle savâbâ",
            "Zâlikel yevmul hakku fe men şâe ittehaze ilâ rabbihi me’âbâ",
            "İnnâ enzernâkum azâben karîbâ, yevme yanzurul mer’u mâ kaddemet yedâhu ve yekûlul kâfiru yâ leytenî kuntu turâbâ"
    
        ],
        arabic: [
            "عَمَّ يَتَسَٓاءَلُونَۚ",
            "عَنِ النَّبَأِ الْعَظٖيمِۙ",
            "اَلَّذٖي هُمْ فٖيهِ مُخْتَلِفُونَؕ",
            "كَلَّا سَيَعْلَمُونَۙ",
            "ثُمَّ كَلَّا سَيَعْلَمُونَ",
            "اَلَمْ نَجْعَلِ الْاَرْضَ مِهَاداًۙ",
            "وَالْجِبَالَ اَوْتَاداًࣕ",
            "وَخَلَقْنَاكُمْ اَزْوَاجاًۙ",
            "وَجَعَلْنَا نَوْمَكُمْ سُبَاتاًۙ",
            "وَجَعَلْنَا الَّيْلَ لِبَاساًۙ",
            "وَجَعَلْنَا النَّهَارَ مَعَاشاًࣕ",
            "وَبَنَيْنَا فَوْقَكُمْ سَبْعاً شِدَاداًۙ",
            "وَجَعَلْنَا سِرَاجاً وَهَّاجاًࣕ",
            "وَاَنْزَلْنَا مِنَ الْمُعْصِرَاتِ مَٓاءً ثَجَّاجاًۙ",
            "لِنُخْرِجَ بِهٖ حَباًّ وَنَبَاتاًۙ",
            "وَجَنَّاتٍ اَلْفَافاًؕ",
            "اِنَّ يَوْمَ الْفَصْلِ كَانَ مٖيقَاتاًۙ",
            "يَوْمَ يُنْفَخُ فِي الصُّورِ فَتَأْتُونَ اَفْوَاجاًۙ",
            "وَفُتِحَتِ السَّمَٓاءُ فَكَانَتْ اَبْوَاباًۙ",
            "وَسُيِّرَتِ الْجِبَالُ فَكَانَتْ سَرَاباًؕ",
            "اِنَّ جَهَنَّمَ كَانَتْ مِرْصَاداًۙ",
            "لِلطَّاغٖينَ مَاٰباًۙ",
            "لَابِثٖينَ فٖيهَٓا اَحْقَاباًۚ",
            "لَا يَذُوقُونَ فٖيهَا بَرْداً وَلَا شَرَاباًۙ",
            "اِلَّا حَمٖيماً وَغَسَّاقاًۙ",
            "جَزَٓاءً وِفَاقاً",
            "اِنَّهُمْ كَانُوا لَا يَرْجُونَ حِسَاباًۙ",
            "وَكَذَّبُوا بِاٰيَاتِنَا كِذَّاباًؕ",
            "وَكُلَّ شَيْءٍ اَحْصَيْنَاهُ كِتَاباً",
            "فَذُوقُوا فَلَنْ نَزٖيدَكُمْ اِلَّا عَذَاباًࣖ",
            "اِنَّ لِلْمُتَّقٖينَ مَفَازاًۙ",
            "حَدَٓائِقَ وَاَعْنَاباًۙ",
            "وَكَوَاعِبَ اَتْرَاباًۙ",
            "وَكَأْساً دِهَاقاًؕ",
            "لَا يَسْمَعُونَ فٖيهَا لَغْواً وَلَا كِذَّاباًۚ",
            "جَزَٓاءً مِنْ رَبِّكَ عَطَٓاءً حِسَاباًۙ",
            "رَبِّ السَّمٰوَاتِ وَالْاَرْضِ وَمَا بَيْنَهُمَاۙ الرَّحْمٰنِ لَا يَمْلِكُونَ مِنْهُ خِطَاباًۙ",
            "يَوْمَ يَقُومُ الرُّوحُ وَالْمَلٰٓئِكَةُ صَفاًّؕ لَا يَتَكَلَّمُونَ اِلَّا مَنْ اَذِنَ لَهُ الرَّحْمٰنُ وَقَالَ صَوَاباً",
            "ذٰلِكَ الْيَوْمُ الْحَقُّۚ فَمَنْ شَٓاءَ اتَّخَذَ اِلٰى رَبِّهٖ مَاٰباً",
            "اِنَّٓا اَنْذَرْنَاكُمْ عَذَاباً قَرٖيباًۚ يَوْمَ يَنْظُرُ الْمَرْءُ مَا قَدَّمَتْ يَدَاهُ وَيَقُولُ الْكَافِرُ يَا لَيْتَنٖي كُنْتُ تُرَاباً",


        ]
    }
};
