<!-- src/components/InstallPWAPrompt.vue -->
<script setup>
import { usePWA } from '../assets/usePwa'
const { isInstallable, showInstallPrompt, installPWA } = usePWA()
</script>


<template>
  <div v-if="isInstallable && showInstallPrompt" class="install-banner">
  <!-- <div  class="install-banner"> -->
    <div class="flex-container column">
      <!-- <span class="install-icon">📱</span> -->
      <span>
        Bu uygulamayı yükle
      </span>
      <button @click="installPWA" class="buton">
        <i class="material-symbols">apk_install</i>
        Yükle
      </button>
      <button @click="showInstallPrompt = false" class="close-button rotate-center">
        <i class="material-symbols">close</i>
      </button>
    </div>
  </div>
</template>



<!-- ekranın ortasında görünür -->
<style scoped>
.flex-container {
    gap: 1rem;
}

.install-banner {
  position: fixed;
  top: 50%; /* Ekranın dikey ortası */
  left: 50%; /* Ekranın yatay ortası */
  transform: translate(-50%, -50%); /* Tam merkeze hizalama */
  background: #24292e;
  color: white;
  padding: 20px; /* Padding'i biraz artırdım */
  z-index: 1000;
  border-radius: 10px; /* Köşeleri yumuşattım */
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Gölge ekledim */
  width: 90%; /* Mobil uyumluluk için */
  max-width: 300px; /* Maksimum genişlik */
}

.install-content {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
  margin: 0 auto;
}

.buton {
  background: #ff6b6b;
  color: white;
  cursor: pointer;
}

.close-button {
  background: transparent;
  color: white;
  border: none;
  cursor: pointer;
  padding: 4px 8px;
  position: absolute; /* Kapatma butonunu sağ üste sabitledim */
  top: 8px;
  right: 8px;
}

.install-button:hover {
  background: #2c974b; /* Hover efekti ekledim */
}

.close-button:hover {
  opacity: 0.8; /* Hover efekti ekledim */
  color: var(--primary) ; /* Hover efekti ekledim */
}




/* ----------------------------------------------
 * Generated by Animista on 2025-1-20 23:9:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */

 .rotate-center:hover {
	-webkit-animation: rotate-center 0.6s ease-in-out both;
	        animation: rotate-center 0.6s ease-in-out both;
}
 @-webkit-keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}
@keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

</style>



<!-- ekranın üstünde görünür -->
<!-- <style scoped>
.install-banner {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  background: #24292e;
  color: white;
  padding: 12px;
  z-index: 1000;
}

.install-content {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
  max-width: 600px;
  margin: 0 auto;
}

.install-button {
  background: #2ea44f;
  color: white;
  border: none;
  padding: 6px 12px;
  border-radius: 6px;
  cursor: pointer;
}

.close-button {
  background: transparent;
  color: white;
  border: none;
  cursor: pointer;
  padding: 4px 8px;
}
</style> -->