<!-- src/components/InstallPWAPrompt.vue -->
<script setup>
import { usePWA } from '../assets/usePwa'
const { isInstallable, showInstallPrompt, installPWA } = usePWA()
</script>


<template>
  <div v-if="isInstallable && showInstallPrompt" class="install-banner">
  <!-- <div  class="install-banner"> -->
    <div class="flex-container column">
      <!-- <span class="install-icon">📱</span> -->
      <p>Daha hızlı ve çevrimdışı erişim için yükle.</p>
      <button @click="installPWA" class="buton">
        <i class="material-symbols">apk_install</i>
        Yükle
      </button>
      <button @click="showInstallPrompt = false" class="close-button rotate-center">
        <i class="material-symbols">close</i>
      </button>
    </div>
  </div>
</template>



<!-- ekranın ortasında görünür -->
<style scoped>
/* .flex-container {
    gap: 1rem;
} */

.install-banner {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: #24292e;
  color: white;
  padding: 20px;
  z-index: 1000;
  border-radius: 10px;
  border: 2px solid var(--primary);
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  box-shadow: rgb(38, 57, 77) 0px 10px 20px -10px;
  width: 90%;
  max-width: 320px;
  text-align: center;
}


.buton {
  background: var(--primary);
  color: white;
  cursor: pointer;
  user-select: none;
  padding: 1.2rem 1.5rem;
}

.close-button {
  background: transparent;
  color: white;
  border: none;
  cursor: pointer;
  user-select: none;
  padding: 4px 8px;
  position: absolute; /* Kapatma butonunu sağ üste sabitledim */
  top: 8px;
  right: 8px;
}

.close-button:hover {
  opacity: 0.8; /* Hover efekti ekledim */
  color: var(--primary) ; /* Hover efekti ekledim */
}




/* ----------------------------------------------
 * Generated by Animista on 2025-1-20 23:9:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */

 .rotate-center:hover {
	-webkit-animation: rotate-center 0.6s ease-in-out both;
	        animation: rotate-center 0.6s ease-in-out both;
}
 @-webkit-keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}
@keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

</style>
